@echo off
echo Starting CookBook application...

echo Starting server...
start cmd /k "cd server && npm start"

echo Starting client...
start cmd /k "cd client && npm start"

echo Both server and client are starting. Please wait a moment... 